pipeline {
    agent any 
    tools {maven 'maven'}
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                bat 'mvn clean package demo/demo/pom.xml'
            }
        }
        
        stage('Test') {
            steps {
                bat 'mvn test demo/demo/pom.xml'
            }
        }
    }
}
