pipeline {
    agent any 
    tools {maven 'maven'}
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                bat 'mvn clean package -f demo/demo/pom.xml'
            }
        }
        
        stage('Test') {
            steps {
                bat 'mvn test -f demo/demo/pom.xml'
            }
        }
    }
}
